
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech

homeassistant: !include conf/homeassistant.yaml

default_config:

#camera: !include conf/media_player/ffmpeg.yaml


panel_custom: !include conf/panel.yaml
#panel_custom: !include panel_custom.yaml

recorder: !include conf/recorder.yaml
logger: !include conf/logger.yaml


image_processing:
  - platform: ctdet
    source:
      - entity_id: camera.door
        name: "hello"
#image_processing:
#  - platform: ctdet
#    source:
#      - entity_id: camera.local_file
#    file_out:
#      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
#      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"

#image_processing:
#  - platform: ctdet
#    topic: 'home-assistan'
#    name: "hello"


#mqtt_basic_async:
#  topic: "home-assistant/mqtt_example"

#mqtt_basic:
#  topic: "home-assistant/mqtt_example"

stream:

weather:
  - platform: darksky
    api_key: !secret darksky_key
#  需要启动 sudo service mosquitto start
mqtt: !include conf/mosquitto.yaml
switch: !include conf/platforms/mqtt/switches.yaml
light:  !include conf/platforms/mqtt/lights.yaml
sensor: !include_dir_merge_list conf/platforms/sensors/
fan: !include conf/platforms/mqtt/fans.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include_dir_merge_named input_boolean



#media_player :
#  - platform: vlc
#    name: VLC player



#light: !include conf/lights/street_light.yaml

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
